name: Download and Commit JSON Content

on:
  schedule:
    - cron: '0 0 * * *' # Chạy hàng ngày lúc 0:00 UTC
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  download-and-commit:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add downloaded_content/
          git commit -m "Update downloaded JSON content" || echo "No changes to commit"
          git push
